### ISSUE TITLE
New release, please

### ISSUE THREAD

**Issue by cpansprout** [gbarr/perl-libnet#3]
Three years ago, I submitted a patch that was applied as 73dc7393a4.  Now this is causing me module installation problems, as MIME-tools is getting a timeout, requiring a forced installation.

Is there any chance we could see a new libnet release some time soon?

**Comment by xpeco** [comment]
Same here.
For example, the issue https://rt.cpan.org/Ticket/Display.html?id=81594 is starting to affect a bundle of dependant modules.

Thank you

**Comment by mbeijen** [comment]
libnet 1.23 is available since August, this ticket can be closed.
https://metacpan.org/release/SHAY/libnet-1.23
